import type { Metadata } from "next";
import "./globals.css";
import { Rubik, Open_Sans } from 'next/font/google';
import { AppProviders } from "./_providers/app-providers";

export const metadata: Metadata = {
  title: "Трансфер",
  description: "Generated by create next app",
};


const rubik = Rubik({
  subsets: ['latin'],
  weight: ["300", "400", "500", "700", "900"],
  variable: "--font-rubik",
});
const openSans = Open_Sans({ subsets: ['latin'], weight: ["300", "400", "600", "700"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${rubik.className} ${openSans.className}`}>
        <AppProviders >
          {children}
        </AppProviders>

      </body>
    </html>
  );
}
